### ISSUE TITLE
Add support of other currencies

### ISSUE THREAD

**Issue by Zjadlbymcos** [Mark-Tomlinson/markup-by-attribute-for-woocommerce#1]
I live in Poland. Our currency symbol is "zł" or "PLN". Can you add support for string currencies? Not all currencies have symbol like $ or €.

**Comment by Mark-Tomlinson** [comment]
I can't decide whether I should add "zł" and "PLN" to the existing edit or if I should remove edits for currency all together.

 

Do you have a preference?

 


--
Mark Tomlinson
"I am not a trouble maker; I'm a catalyst for change."

 
 

Sent: Wednesday, September 12, 2018 at 4:24 PM

**Comment by Zjadlbymcos** [comment]
If my opinion matters I think you should let enduser decide what prefix or postfix he wants. Even if that will be "lama".

But the best option will be to use properties from WooCommerce. There are option to choose beetween currencies and position (prefix, postfix). There's no need to duplicate this feature in your plugin.

WooCommerce -> Settings -> General -> Currency options
![ Currency options](https://user-images.githubusercontent.com/11710437/45473601-c621fa80-b737-11e8-9115-46dabd19a5e7.png)

**Comment by Mark-Tomlinson** [comment]
And that is exactly why your opinion matters.

 

I'll set it up to use the WooCommerce currency options and get a new version out probably by the end of next week.
 

--
Mark Tomlinson
"I am not a trouble maker; I'm a catalyst for change."

 
 

Sent: Thursday, September 13, 2018 at 2:32 AM

**Comment by Mark-Tomlinson** [comment]
Still working on this. The change was fairly easy, but I need to do some extensive testing.  Will have it out in a few days.
