### ISSUE TITLE
Update for WP 5.3 & PHP 7.3

### ISSUE THREAD

**Issue by Kehec** [Mark-Tomlinson/markup-by-attribute-for-woocommerce#10]
After update on WP 5.3 the following Fatal Error appears:

Fatal error: Uncaught Error: Class 'MT2MBA_UTILITY_GENERAL' not found in 

wp-content/plugins/markup-by-attribute-for-woocommerce-master/markup-by-attribute-for-woocommerce.php:87 Stack trace: #5 

wp-includes/class-wp-hook.php(288): mt2mba_main('') #1 
wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array) #2 
wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 
wp-content/plugins/woocommerce/includes/class-woocommerce.php(561): do_action('woocommerce_ini...') #4 
wp-includes/class-wp-hook.php(288): WooCommerce->init('') #5 
wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array) #6 
wp-content/plugins/markup-by-attribute-for-woocommerce-master/markup-by-attribute-for-woocommerce.php on line 87

**Comment by Mark-Tomlinson** [comment]
I am unable to recreate the error in WordPress 5.3 and PHP 7.3.11 (WooCommerce 3.8.0, but that shouldn't matter).

 

This indicates a problem with the autoload function, in that it can't locate ../markup-by-attribute-for-woocommerce/src/utility/general.php.

 

I notice that your Markup by Attribute plugin directory is named /markup-by-attribute-for-woocommerce-master. Is there a reason “-master” is appended to the directory?

 

--
Mark Tomlinson
“I am not a trouble maker; I'm a catalyst for change.”

 
 

Sent: Sunday, November 17, 2019 at 11:08 AM

**Comment by Kehec** [comment]
i renamed the dictionary but it seems to have problems with my current installation of WP and or Woocommerce. I just deactivated any plugins and theme, but nothing worked out good. workaround: i`m going to set up both on an fresh environment and it seems to work. Maybe I will detect the trouble maker afterwards, will let you know.
And thanks for your quick response!
