### ISSUE TITLE
Not charging extra at checkout

### ISSUE THREAD

**Issue by matthew6s** [Mark-Tomlinson/markup-by-attribute-for-woocommerce#13]
The extra charge shows on my product page. But when I go to the cart it does not add the extra amount to the cart.

**Comment by Mark-Tomlinson** [comment]
No, it does not add the markup at checkout. You have to run the `Set regular prices` function and it will add the markup to the product variations.

https://github.com/Mark-Tomlinson/markup-by-attribute-for-woocommerce/wiki/Usage

**Comment by surfer77** [comment]
Is there a way to run `Set regular prices` in bulk as I am adding the plugin after the complete store is setup?

**Comment by Mark-Tomlinson** [comment]
`Set regular price` and `Set sale price` are bulk, of a sort, in that they set the prices of all the variations of a product. I'm not aware of any feature of WooCommerce or another plugin that would allow you to run `Set regular price` for all products at once.

If you have already priced all your variations, you can run `Set regular price` again to capture the markup.
