### ISSUE TITLE
How can I change the "Add £50.00 for AG"

### ISSUE THREAD

**Issue by christiansingian** [Mark-Tomlinson/markup-by-attribute-for-woocommerce#18]
I want to rephrase this text

**Comment by Mark-Tomlinson** [comment]
There is no easy way to do that. There are two things you could try, though.

- If you are familiar with PHP and the WordPress plugin editor, you can edit line 227 in Markup by Attribute/src/utility/general.php. However, this will revert the next time the plugin is updated.

- The other is to set up a translation file with only two entries for "Add %1$s for %2$s" and "Subtract %1$s for %2$s". This should survive plugin updates, but is more difficult to accomplish.

In either case, the plugin replaces the string '%1$s' with the markup and '%2$s' with the option.
