### ISSUE TITLE
Add support for translating plugins

### ISSUE THREAD

**Issue by Zjadlbymcos** [Mark-Tomlinson/markup-by-attribute-for-woocommerce#2]
I recently try to localize some text strings and Loco Translate can't handle it. Loco finds only 4 string able to translate. There is no template file for translates. Can you add support for language localizing your plugin?
![Screenshot from Loco Translate](https://user-images.githubusercontent.com/11710437/45457220-3dcb3780-b6ee-11e8-97b5-b13c865622f9.png)

**Comment by Mark-Tomlinson** [comment]
I can do that.  It will take me a while, though.  I'm sort of new at this and not familiar with setting up the templates.
 


--
Mark Tomlinson
"I am not a trouble maker; I'm a catalyst for change."

 
 

Sent: Wednesday, September 12, 2018 at 5:45 PM

**Comment by Mark-Tomlinson** [comment]
I'm going to leave this issue open and start working on internationalization. I can not give a timetable since this is new to me.

**Comment by Mark-Tomlinson** [comment]
Okay!  The /languages file now contains markup-by-attribute.pot. Have at it!

Can you send me any translations? I'd like to include them in future copies.

**Comment by Zjadlbymcos** [comment]
I'm ready with commit for pull request. Can you add me permission in repository for that?

**Comment by Zjadlbymcos** [comment]
Sure. [Here's pull request](https://github.com/Mark-Tomlinson/markup-by-attribute-for-woocommerce/pull/5) ^.^
