### ISSUE TITLE
Hide breakdown of the price modifications

### ISSUE THREAD

**Issue by janenco** [Mark-Tomlinson/markup-by-attribute-for-woocommerce#20]
What a wonderfully made plugin!
I would like to thank the author for making this.

It works perfect, yet I would like to hide the breakdown of the price modification.
Is this possible? It kind of looks messy, and it's even in a different language than the rest of my website.

Thanks :)

**Comment by Mark-Tomlinson** [comment]
Thanks for the kind words. Yes, there are actually two ways to hide the price breakdown, and I recommend both.

First, you will not want to create the price breakdown when you set the prices. You can accomplish this in the Markup by Attribute settings. In your dashboard, go to WooCommerce >> Settings >> Products >> Markup by Attribute and scroll to "Description Behavior". Select "Do NOT add pricing information to the description field". This will prevent Markup by Attribute from creating any _new_ price breakdowns,

However, the above won't eliminate any pricing information that is already stored with variations. You could go through everything and reprice them, but that would take a painful amount of time.  Instead, add the following to the Additional CSS on your Customize page.
```
#mbainfo { display: none; }
```
For more information, [here is another thread](https://wordpress.org/support/topic/remove-attribute-description/) where I discuss this.
