### ISSUE TITLE
Do NOT show the markup in the options drop-down box

### ISSUE THREAD

**Issue by whis** [Mark-Tomlinson/markup-by-attribute-for-woocommerce#6]
An option "Do NOT show the markup in the options drop-down box." makes the dropdown menu print slug instead of a name of the attributes.

![image](https://user-images.githubusercontent.com/749071/50588749-ca5b5a80-0e83-11e9-9763-edb11d3afbf1.png)
![image](https://user-images.githubusercontent.com/749071/50588756-d6471c80-0e83-11e9-8513-d434f20424f4.png)
![image](https://user-images.githubusercontent.com/749071/50588782-eeb73700-0e83-11e9-82fe-795c3f3e68ee.png)

**Comment by Mark-Tomlinson** [comment]
Crap. You're right. I'll look into fixing that right away.

**Comment by Mark-Tomlinson** [comment]
Fixed with version 3.2.

Thanks for calling it to my attention.
