### ISSUE TITLE
[Suggestion] Multiple markups

### ISSUE THREAD

**Issue by whis** [Mark-Tomlinson/markup-by-attribute-for-woocommerce#8]
Would it be possible to add support for multiple markups?
For example: "+10% -0.1" which would apply in the order as written, hence: X * (1 + 0.1) + (-0.1)

**Comment by Mark-Tomlinson** [comment]
I hadn't thought about doing that.  I'd probably seperate them with the '|' bar so it would be written as "+10%|-0.1".  Can you give me an example of how that might be used?

 

--
Mark Tomlinson
"I am not a trouble maker; I'm a catalyst for change."

 
 

Sent: Wednesday, January 02, 2019 at 12:21 PM

**Comment by whis** [comment]
It could be used for [psychologic pricing](https://en.wikipedia.org/wiki/Psychological_pricing). It's not necessary but would be a nice feature to have.

**Comment by Mark-Tomlinson** [comment]
Thanks for the suggestion. Am closing the issue and will return to it next time I do a major feature update.
