### ISSUE TITLE
Price didn't update after selecting marked up attribute

### ISSUE THREAD

**Issue by louson21** [Mark-Tomlinson/markup-by-attribute-for-woocommerce#9]

**Comment by Mark-Tomlinson** [comment]
I'm afraid I'll need a little more information than that to debug your problem. But first, here are the Usage instructions, https://github.com/Mark-Tomlinson/markup-by-attribute-for-woocommerce/wiki/Usage. Specifically, I'm wondering if you ran the `Set regular price` function.

**Comment by louson21** [comment]
Thanks it worked.
